- name: Install Elastic
  hosts: [master, workers]
  become: True
  gather_facts: true

  pre_tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
  
  roles:
    - role:  install_software
      vars:
        packages_to_install: 
          - elasticsearch

- name: Install kibana
  hosts: [kibana]
  become: True
  gather_facts: true

  pre_tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
  
  roles:
    - role:  install_software
      vars:
        packages_to_install: 
          - kibana
