- name: Install Elastic
  hosts: all
  become: True
  gather_facts: false

  pre_tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
  
  roles:
    - install_elastic

- name: configure master node
  hosts: master
  become: true
  gather_facts: false

  roles:
    - generate_enrollment_token
  tasks:
    - name: Print Elasticsearch enrollment token
      debug:
        msg: "Elasticsearch enrollment token is {{ elasticsearch_enrollment_token }}"

# TODO:

#- name: Copy configs to server  # use hostname to copy correct config to correct server
#  hosts: all

#- name: handler for restat elastic