- name: Install Elastic
  hosts: all
  become: True
  gather_facts: false

  pre_tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
  
  roles:
    - install_elastic

- name: configure elasticsearch nodes
  hosts: master
  become: true
  gather_facts: true

  roles:
    - copy_config_to_server

  tasks:
    - name: Flush handlers after copy_config_to_server
      meta: flush_handlers

    - name: Other tasks after handler has run
      debug:
        msg: "Handlers have been triggered, proceeding with other tasks..."

    - include_role:
        name: update_elastic_password
    - include_role:
        name: generate_enrollment_token

    - name: Print Elasticsearch enrollment token
      debug:
        msg: "Elasticsearch enrollment token is {{ elasticsearch_enrollment_token }}"

    - name: Print Elasticsearch password
      debug:
        msg: "Elasticsearch password is: {{ elasticsearch_password }}"

- name: configure workers
  hosts: workers
  become: true
  gather_facts: true

  roles:
    - role: add_node_to_cluster
    - role: copy_config_to_server

# TODO: add test from master: curl -ku elastic:<pass> https://<ip>:9200/_cat/nodes