---
- name: Create Elasticsearch enrollment token
  command: /usr/share/elasticsearch/bin/elasticsearch-reset-password -bs -u elastic
  register: elastic_password

- name: Set Elasticsearch password
  set_fact:
    elasticsearch_password: "{{ elastic_password.stdout }}"