# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/filebeat/8.15/filebeat-module-kibana.html

- module: kibana
  log:
    enabled: true
    var.paths:
      - "/var/log/kibana/*.log"

  # Audit logs
  audit:
    enabled: false
