# Module: nginx
# Docs: https://www.elastic.co/guide/en/beats/filebeat/8.15/filebeat-module-nginx.html

- module: nginx
  access:
    enabled: true
    var.paths:
      - "/var/log/nginx/*.log"

  # Error logs
  error:
    enabled: false

  # Ingress-nginx controller logs. This is disabled by default. It could be used in Kubernetes environments to parse ingress-nginx logs
  ingress_controller:
    enabled: false
