---
# TODO: як перевірити, що файл дійсно змінився?
- name: Copy Elasticsearch config file based on hostname
  ansible.builtin.copy:
    src: "files/{{ ansible_hostname }}.yaml"
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '0644'
  notify: Reload systemd and enable/start Elasticsearch service